import Head from 'next/head';
import { NextPage } from 'next';
import axios from '@/utils/axios';
import { PostItem } from '@/interfaces/post.interface';
import React from 'react';
import { paginate } from '@/utils/paginate';
import { Pagination, PostMain } from '@/components';
//=========================================================================================================================
interface HomeProps {
	posts: PostItem[];
}
//=========================================================================================================================

// Главная страница приложения
const HomePage: NextPage<HomeProps> = ({ posts }) => {
	const [currentPage, setCurrentPage] = React.useState<number>(1);
	const pageSize = 15;

	const onPageChange = (page: number) => {
		setCurrentPage(page);
	};

	const paginatedPosts = paginate(posts, currentPage, pageSize);

	return (
		<>
			<Head>
				<title>Hexfair Blog</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				{posts && paginatedPosts.map(obj =>
					<PostMain
						key={obj._id}
						id={obj._id}
						title={obj.title}
						text={obj.text}
						imageUrl={obj.imageUrl ? obj.imageUrl : ''}
						date={obj.createdAt}
						authorName={obj.author?.fullName}
						authorAvatar={obj.author?.avatarUrl}
						tags={obj.tags}
						viewsCount={obj.viewsCount}
					/>
				)}
				<Pagination
					items={posts.length}
					currentPage={currentPage}
					pageSize={pageSize}
					onPageChange={onPageChange}
				/>
			</div>
		</>
	);
};

export const getServerSideProps = async () => {
	try {
		const { data } = await axios.get<PostItem[]>('/posts');
		return {
			props: {
				posts: data
			}
		};
	} catch (err) {
		console.error(err);
	}

	return {
		props: {
			posts: []
		}
	};
};


export default HomePage;